## Review of the Literature

### Miscellaneous

1. @Abe2015-lx offer an interesting description of the role of the lamina cribrosa in the pathophysiology of glaucoma. The lamina cribrosa is a sieve-like structure that allows the passage of retinal ganglion cell axons from the eye to the brain. It is composed of connective tissue and is supported by the sclera. The lamina cribrosa is also a site of mechanical stress, as it is subjected to intraocular pressure and cerebrospinal fluid pressure. It has been suggested that the lamina cribrosa may be a site of axonal injury in glaucoma, and that changes in it may be an early indicator of glaucomatous damage. Specifically, a thinner LC is associated with glaucomatous damages.
They suggest a very interesting hypothesis: glaucoma is caused by the trans-laminar pressure gradient (i.e. the difference between IOP and cerebrospinal fluid pressure). The hypothesis is supported by the work of @Ren2010-nq: a low cerebrospinal fluid pressure (CSF-P) is associated with open-angle glaucoma in eyes with normal intraocular pressure (IOP). 

::: {.callout-note title="Conclusion from @Ren2010-nq"}
In open-angle glaucoma with normal IOP, cerebrospinal fluid pressure (CSF-P) is abnormally low, leading to an abnormally high trans-lamina cribrosa pressure difference. Pathogenetically, a low CSF-P in normal-IOP glaucoma may be similar to a high IOP in high-IOP glaucoma. Consequently, the glaucomatous visual field defect is positively correlated with the trans-lamina cribrosa pressure difference and inversely correlated with the CSF-P. In nonglaucomatous subjects, CSF-P, blood pressure, and IOP are significantly associated with each other
:::

::: {.callout-note collapse="true" title="More about CSF-P"}

@JONAS201567 offer an interesting review on the CSF-P and its role with the physiology of the eye.
- Thicker subfoveal choroidal thickness was associated with higher estimated CSFP.
- Larger retinal vein diameters and higher vein-to-artery diameter ratios were significantly associated with higher estimated CSFP (P = 0.001). In contrast, retinal arterial diameters were not significantly associated with estimated CSFP nor were other microvascular abnormalities such as arteriovenous crossing signs. In a reverse manner, higher estimated CSFP was correlated with wider retinal veins and higher vein-to-artery diameter ratio, but not with retinal artery diameters or other retinal microvascular abnormalities. 
:::

2. @werffNewSingleParameterOcular1981 suggests to use another metric to estimate the rigidity:
$$
\Delta V = \frac{1}{K} (P_2^{1/3} - P_1^{1/3})
$$
where $\Delta V$ is the change in volume and $P_2$ and $P_1$ are the intraocular pressures at the two measurements. Other definitions are also listed in section @sec-NoninvasiveClinicalMeasurementOfOcularRigidity and @sec-OcularRigidityInLivingHumanEyes.


###  Structural Measurements for Monitoring Change in Glaucoma: Comparing Retinal Nerve Fiber Layer Thickness With Minimum Rim Width and Area 



Structural measurements are noisy. @10.1167/iovs.15-16701 propose to use the LSNR (Longitudinal Signal-to-Noise Ratio). Instead of comparing the slope of a structural measurement over time, they propose to compare the slope divided by the standard deviation of the residuals. This is a measure of how much signal there is in the noise. The more negative the LSNR, the more likely it is that the slope is real and not just noise. They compare three structural measurements: the retinal nerve fiber layer thickness (RNFLT), the minimum rim width (MRW) and the minimum rim area (MRA). They find that the RNFLT has a better LSNR than MRW or MRA. Although MRW and MRA may be more sensitive for early detection of glaucomatous damage, these data suggest that RNFLT may be preferable for monitoring change.
Cohort: 157 eyes of 157 participants with high-risk ocular hypertension or non–end-stage glaucoma (mean deviation [MD] from −22 to +3 dB). Participants were tested approximately every 6 months for at least six visits. 
```{python}
#| echo: false
#| warning: false
import seaborn as sns
import matplotlib.pyplot as plt

LSNR_RNFLT = -0.58
LSNR_MRW = -0.44
LSNR_MRA = -0.23
with plt.xkcd():
    sns.barplot(x=["RNFLT", "MRW", "MRA"], y=[LSNR_RNFLT, LSNR_MRW, LSNR_MRA])
    plt.ylabel("LSNR ($y^{-1}$)")
    plt.title("Longitudinal Signal-to-Noise Ratio for Structural Measurements")
    plt.show()
```

###  Clinical Utility of Bruch Membrane Opening-Minimum Rim Width for Detecting Early Glaucoma in Myopic Eyes

@Park2021-dd conduct a study to determine the diagnostic value of BMO-MRW compared with peripapillary retinal nerve fiber layer (pRNFL) thickness for detecting early glaucoma in patients with moderate to severe myopia. Global analyses for the discrimination of early glaucoma in all myopic subjects showed comparable AUCs between BMO-MRW and pRNFL thickness [AUC 0.952 (95% confidence interval, 0.918-0.975) and 0.934 (95% confidence interval, 0.896-0.961), respectively, P=0.345]. However, in sectoral analysis, BMO-MRW showed significantly better diagnostic performance than pRNFL thickness except for the superotemporal sector. 
```{python}
#| echo: false
#| warning: false
G_BMO_MRW_MYOPIC = 341.7
G_BMO_MRW_GLAUC_SUS = 293.5
G_BMO_MRW_EARLY_GLAUC = 212.7
G_RNFLT_MYOPIC = 87.8
G_RNFLT_GLAUC_SUS = 81.9
G_RNFLT_EARLY_GLAUC = 64.4
with plt.xkcd():
    fig, axes = plt.subplots(1, 2, figsize=(10, 4))

    sns.barplot(x=["Myopic", "Glaucoma Suspect", "Early Glaucoma"], y=[G_BMO_MRW_MYOPIC, G_BMO_MRW_GLAUC_SUS, G_BMO_MRW_EARLY_GLAUC], ax=axes[0])
    axes[0].set_ylabel("Global BMO-MRW (\u03bcm)")
    axes[0].set_title("Global BMO-MRW in Myopic Eyes")
    sns.barplot(x=["Myopic", "Glaucoma Suspect", "Early Glaucoma"], y=[G_RNFLT_MYOPIC, G_RNFLT_GLAUC_SUS, G_RNFLT_EARLY_GLAUC], ax=axes[1])
    axes[1].set_ylabel("Global RNFLT (\u03bcm)")
    axes[1].set_title("Global RNFLT in Myopic Eyes")
    plt.tight_layout()
    plt.show()
```

###  The Association Between Ocular Rigidity and Neuroretinal Damage in Glaucoma 

@Sayah2020-ym aims to evaluate the relationship between OR and neuroretinal damage caused by glaucoma.
 Significant positive correlations were found between OR and minimum GCC thickness (r = 0.325, P = 0.001), average GCC thickness (r = 0.320, P = 0.002), rim area (r = 0.344, P < 0.001), and RNFL thickness in the superior (r = 0.225, P = 0.023), and inferior (r = 0.281, P = 0.004) quadrants. These correlations were generally greater than those found for CCT, CH, and CRF. Furthermore, no correlation was found between OR and corneal biomechanical parameters.
 Cohort: 108 subjects (22 healthy, 23 suspected glaucoma, and 63 glaucoma (early to advance)).
 The main results are sumarized in @fig-ocular-rigidity-neuroretinal-damage, which represents the partial correlation between OR and neuroretinal damage, adjusted for age, sex, and axial length.
```{python}
#| label: fig-ocular-rigidity-neuroretinal-damage
#| echo: false
#| warning: false
NEURORETINAL_RIM_AREA = 0.327
MINIMUM_GCC_THICKNESS = 0.357
AVG_GCC_THICKNESS = 0.344
AVG_RNFL_THICKNESS = 0.331
SUP_QUA_RNFL_THICKNESS = 0.296
TEMPO_QUA_RNFL_THICKNESS = 0.108
INFO_QUAD_RNFL_THICKNESS = 0.317

with plt.xkcd():
    fig, ax = plt.subplots(1, 1, figsize=(10, 4))

    sns.barplot(x=["Rim Area", "Min GCC\nThickness", "Avg GCC\nThickness", "Avg RNFL\nThickness", "Sup. Quad\nRNFL Thickness", "Temp. Quad\nRNFL Thickness", "Inf Quad\n Thickness"], y=[NEURORETINAL_RIM_AREA, MINIMUM_GCC_THICKNESS, AVG_GCC_THICKNESS, AVG_RNFL_THICKNESS, SUP_QUA_RNFL_THICKNESS, TEMPO_QUA_RNFL_THICKNESS, INFO_QUAD_RNFL_THICKNESS], ax=ax)
    ax.set_ylabel("Correlation Coefficient (r)")
    ax.set_title("Correlation Between Ocular Rigidity and Neuroretinal Damage")
    plt.tight_layout()
    plt.show()
```


### Association between ocular biometric parameters and scleral rigidity as measured by fundus pulsation optical coherence elastography in eyes with and without glaucoma

@Bojikian2026-sq published a study to evaluate the association between ocular biometric parameters and scleral rigidity as measured by fundus pulsation optical coherence elastography (FP-OCE) in eyes with and without glaucoma. The study included 58 eyes with glaucoma and 36 control eyes. In @fig-scleral-rigidity-ocular-biometric-parameters, we see the choroidal max strain in glaucoma vs normal eyes they obtain. In short, higher maximum choroidal strain (which is either a more pulsatile choroid or a thinner choroid) is midly associated with glaucoma, which in turns indicate that a lower ocular rigidity is associated with glaucoma.
```{python}
# | echo: false
# | warning: false
# | label: fig-scleral-rigidity-ocular-biometric-parameters

choroidal_max_strain_glaucoma = 0.0117
choroidal_max_strain_normal = 0.0103

with plt.xkcd():
    fig, ax = plt.subplots(1, 1, figsize=(6, 4))

    sns.barplot(x=["Glaucoma", "Normal"], y=[choroidal_max_strain_glaucoma, choroidal_max_strain_normal], ax=ax)
    ax.set_ylabel("Choroidal Max Strain")
    ax.set_title("Choroidal Max Strain in Glaucoma vs Normal Eyes")
    plt.tight_layout()
    plt.show()
```


### Non-invasive Clinical Measurement of Ocular Rigidity and Comparison to Biomechanical and Morphological Parameters in Glaucomatous and Healthy Subjects {#sec-NoninvasiveClinicalMeasurementOfOcularRigidity}

@maNoninvasiveClinicalMeasurement2021 offer almost the same methodology as we do in this study, to ONH videos. They show that there is a stronger correlation between ocular rigidity and sclearal stiffness (R=0.62, measured using the stiffness parameter at the highest concavity [SP-HC]) vs corneal stiffness (stiffness parameter at the first applanation [SP-A1], R=0.41).  There is a positive corelation with the static pressure-volume ratio (P/V, R=0.72). They do the same linearization of $\Delta V \approx 4\pi R^2\Delta CT$. They define $R$ as half the axial length. 

The coneaosclera properties were measured using with a Corvis ST, a non contact tonometer coupled with a high-speed Scheimpflug camera. The corneal stiffness was measured using the stiffness parameter at the first applanation (SP-A1). The scleral stiffness was measured using the stiffness parameter at the highest concavity (SP-HC). 

### Ocular Rigidity in Living Human Eyes {#sec-OcularRigidityInLivingHumanEyes}
 
@pallikarisOcularRigidityLiving2005 proceed with an actual measurement of the rigidity (unfortunately, not defined as we did, i.e, they define $K = \frac{\Delta P}{\Delta V}$ ). They inject saline in the eye by interval, until they reach an IOP of 60 mmHg or 200 μL of saline. The average $R^2$ they obtain is 0.92 (*maybe the linearization of the relation is actually a good idea*; they indicate the linear relationship was the best fit they got). 
They also reference the work of @silverPressurevolumeRelationLiving2000, that indicate that the best fit for the pressure-volume relationship is:
$$
\Delta V = V \cdot (C+C_0\log{P} + C_1 \cdot P)
$$
where $C$, $C_0$ and $C_1$ are numerical constants.