# Correlation analysis {#sec-correlation}

## Correlation analysis - Structural and biomechanical characteristics
In this section, we focus on establishing the correlation between each visit measurements (taken at the same time) and biomechanicals characteristics extracted from the data. Each point therefore represents a visit, and the correlation is computed across all visits. The correlation coefficient is computed using the Pearson method.
Let's first visualize what correlates with the intraocular pressure (IOP) measured.
{{< embed ../../notebooks/plots.ipynb#fig-K-vs-IOP-vs-dCT-vs-dV >}}

We do not see a strong correlation between the intraocular pressure and the ocular rigidity, change in choroidal thickness or change in ocular volume. On the other hand, we have a pretty good correlation between the **ocular pulse amplitude** (OPA) and the change in choroidal thickness or change in ocular volume (@fig-deltact-dv-vs-opa ). 
{{< embed ../../notebooks/plots.ipynb#fig-deltaCT-dV-vs-OPA >}}

Let's plot how the change in choroidal thickness correlates with the minimal choroidal thickness (@fig-ct-vs-delta-ct). The thicker the choroid, the more it can change in thickness. 
{{< embed ../../notebooks/plots.ipynb#fig-ct-vs-delta-ct >}} 

We observe another mild correlation between the axial length and the change in choroidal thickness and the minimal choroidal thickness (@fig-axial-length-vs-delta-ct-and-ct). This is fairly consistent with the literature: myopic eyes (longer axial length) tend to have thinner choroids (@Meng2023-jk)

{{< embed ../../notebooks/plots.ipynb#fig-axial-length-vs-delta-ct-and-ct >}}

Another potentially interesting correlation is between age and the choroidal thickness (previously documented -@SADEGHI2025167-, approximately 12.7-15.6 μm per decade). In our cohort, we observe a stronger trend (around 25 μm per decade) between age and the change in choroidal thickness (@fig-k-deltact-deltav-vs-age).

{{< embed ../../notebooks/plots.ipynb#fig-K-deltaCT-deltaV-vs-age  >}}

## Correlation analysis - ONH characteristics

In this section, we focus on establishing a correlation between the macular properties (choroidal thickness, ocular rigidity, change in choroidal thickness, etcc.) and the optic nerve head (ONH) characteristics.

First, let's observe how the minimal rim width (MRW) correlates with the ocular rigidity, depending on the quadrants on the ONH (@fig-k-vs-mrw). We observe a mild correlation between the ocular rigidity and the MRW, especially in the nasal quadrants. Mostly, this correlation is lost when testing against the axial length, CT, ΔCT or ΔV.


{{< embed ../../notebooks/plots.ipynb#fig-K-vs-MRW  >}}

A similar trend (correlation between K and the ONH characteristics, but not with the other biomechanical characteristics) is observed when looking at the circular RNFL thickness  (@fig-k-vs-rnfl). 

{{< embed ../../notebooks/plots.ipynb#fig-K-vs-RNFL >}}
::: {.callout-warning}
In @fig-k-vs-rnfl, some points were filtered (outliers, quantile=0.999).
:::

## Correlation analysis - Visual field characteristics


In our cohort, the rigidity does not correlate with any of the visual field metrics (MD, PSD, VFI) (@fig-k-vs-md-psd-vfi). However, we observe a tiny correlation between the change in choroidal thickness and the visual field metrics (@fig-ct-vs-md-psd-vfi).

{{< embed ../../notebooks/plots.ipynb#fig-K-vs-MD-PSD-VFI >}}

{{< embed ../../notebooks/plots.ipynb#fig-CT-vs-MD-PSD-VFI >}}


We can compare with the correlation between the IOP and the visual field metrics (@fig-iop-vs-md-psd-vfi). Overall, the IOP correlates better with the visual field metrics than the ocular rigidity or the choroidal thickness.
{{< embed ../../notebooks/plots.ipynb#fig-IOP-vs-MD-PSD-VFI >}}